### PR TITLE
fix(honkit): upgrading to cheerio 1.x

### LINKED ISSUE #280: Upgrade cheerio to resolve security warnings
Honkit uses cheerio 0.20.0, which has some child dependencies that throw security notices. While I imagine none of these are exploitable, it's still noise in security scans given they've been fixed upstream.

Unfortunately, there's breaking changes in the `1.0-rc` versions that cause test failures: https://github.com/cheeriojs/cheerio/releases/tag/1.0.0-rc.2

The errors seem to stem from `dom.ts`'s `parse` and `root` functions. I'm actually a little confused how they are supposed to work today, because it seems like in some cases they return cheerio itself and others just an element object. I think what's happening is that in 0.20.0, the `first()` call is always returning empty, so the other case is never triggered.

By using `const $ = cheerio.load(html, { _useHtmlParser2: true });` all of the mocha tests pass, but snapshot tests fail with clear HTML errors such as extra `<html>` tags.

```
$ yarn audit
yarn audit v1.22.19
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Inefficient Regular Expression Complexity in nth-check       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ nth-check                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ honkit                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ honkit > cheerio > css-select > nth-check                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1070415                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Inefficient Regular Expression Complexity in nth-check       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ nth-check                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ honkit                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ honkit > juice > cheerio > css-select > nth-check            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1070415                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Inefficient Regular Expression Complexity in nth-check       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ nth-check                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ honkit                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ honkit > @honkit/asciidoc > @honkit/html > cheerio >         │
│               │ css-select > nth-check                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1070415                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Insufficient Granularity of Access Control in JSDom          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jsdom                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=16.5.0                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ honkit                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ honkit > cheerio > jsdom                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1075671                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Insufficient Granularity of Access Control in JSDom          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jsdom                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=16.5.0                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ honkit                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ honkit > @honkit/asciidoc > @honkit/html > cheerio > jsdom   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1075671                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by azu**
This PR update cheerio to 1.0.0-rc.12.
It includes @deviantintegral works.

fix #280 
fix #281 
Maybe related #298

### CODE REVIEW

File: packages/honkit/src/output/modifiers/annotateText.ts [hunk 1]
```diff
@@ -24,32 +23,35 @@ function replaceText($, el, search, replace, text_only) {
...
 
-                    // The new value.
                     new_val = val.replace(search, replace);
 
                     // Only replace text if the new value is actually different!
                     if (new_val !== val) {
                         if (!text_only && /</.test(new_val)) {
                             // The new value contains HTML, set it in a slower but far more
                             // robust way.
-                            $(node).before(new_val);
```
Comment (azu) [inline packages/honkit/src/output/modifiers/annotateText.ts:35]: It seems that `before` does not work.

I use `replaceWIth` instead of it.

Comment (azu) [reply packages/honkit/src/output/modifiers/annotateText.ts:35]: Based on [Replace a textNode with HTML text in Javascript? - Stack Overflow](https://stackoverflow.com/questions/15553280/replace-a-textnode-with-html-text-in-javascript)

**Comment by deviantintegral** [comment]
Thank you! 👏
