### PR TITLE
fix(markdown): convert trailing spaces to <br>

### LINKED ISSUE #420: can not render line break
## Summary

I can not write something multiline.
In markdown, I can write "hello world" in two lines like this:

```markdown
hello<whitespace><whitespace>
world
```
GitHub renders it like below:

---

hello  
world

---

"hello world" will appear on two lines, but in honkit it will be rendered in three lines.

- HonKit version: 5.1.4

## Step to reproduce

1. init a book
2. write something need to be in the same paragraph but in multilines
3. honkit serve

I need to write some lyrics in the markdown, so they should in the same paragraph.

image

### PR DESCRIPTION
**Pull request by davmillar**
The markup-it syntax parser for markdown now coerces a trailing double space to a <br> tag to provide the expected line break behavior. Tests have been added as well.

Closes #420

### CODE REVIEW

File: packages/@honkit/markup-it/syntaxes/markdown/document.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ function cleanupText(src) {
         .replace(/\t/g, "    ")
         .replace(/\u00a0/g, " ")
         .replace(/\u2424/g, "\n")
+        .replace(/  \n/g, "<br>")
```
Comment (azu) [inline packages/@honkit/markup-it/syntaxes/markdown/document.js:16]: lint error is here.

Comment (davmillar) [reply packages/@honkit/markup-it/syntaxes/markdown/document.js]: My bad, pushed a fix. Thanks for pointing it out.

**Comment by azu** [comment]
Thanks!
