### PR TITLE
fix(markdown): Do not force convert Indented CodeBlock to Fenced code blocks

### LINKED ISSUE #58: gitbook-plugin-uml does not work
## Summary

https://github.com/vowstar/gitbook-plugin-uml does not work on Honkit

- HonKit version: 3.3.10

## Step to reproduce

- Link to code example: https://github.com/azu/honkit-example-gitbook-plugin-uml

## Expected results

Render the uml correctly.

## Actual results

Rendering error.

## Note

https://github.com/vowstar/gitbook-plugin-uml/blob/99ad7443d2a2c051c2327c7ebda63a0ca19f1621/index.js#L41
Dump the `code` variable and I noticed the differnece between GitBook and HonKit

GitBook

    @startuml

        Class Stage
        Class Timeout {
            +constructor:function(cfg)
            +timeout:function(ctx)
            +overdue:function(ctx)
            +stage: Stage
        }
        Stage <|-- Timeout

    @enduml

HonKit

    @startuml

    ```
    Class Stage
    Class Timeout {
        +constructor:function(cfg)
        +timeout:function(ctx)
        +overdue:function(ctx)
        +stage: Stage
    }
    Stage <|-- Timeout
    ```

    @enduml

### PR DESCRIPTION
**Pull request by azu**
This behavior break Fenced code blocks macro like https://github.com/vowstar/gitbook-plugin-uml

- `page:before`: Convert Fenced code blocks to Block Tags that includes Indented CodeBlock
- `plugin.prepare`: Convert Indented CodeBlock to Fenced code blocks <- This break the plugin and This commit fix it
- Convert Block Tags by plugins

This commit remove `plugin.prepare` behavior that convert Indented CodeBlock to Fenced code blocks.
As a result, the plugin receive Indented CodeBlock's content instead of triple tick content.

So, it will make https://github.com/vowstar/gitbook-plugin-uml work in HonKit.

fix #58

### CODE REVIEW

File: packages/@honkit/markup-it/syntaxes/markdown/code.js [hunk 1]
```diff
@@ -20,16 +20,14 @@ const blockRule = MarkupIt.Rule(MarkupIt.BLOCKS.CODE)
     .regExp(reBlock.code, (state, match) => {
         let inner = match[0];
 
-        // Remove indentation
-        inner = inner.replace(/^( {4}|\t)/gm, "");
```
Comment (azu) [inline packages/@honkit/markup-it/syntaxes/markdown/code.js:24]: Originally, This force convert Indented CodeBlock to Fenced code blocks.
