### PR TITLE
fix(honkit): fix to load @scope/honkit-plugin-name

### LINKED ISSUE #68: honkit plugin + scoped module is not loaded
## Summary

`@scope/honkit-plugin-xxx` is not loaded

- HonKit version: lastest

## Step to reproduce

`@ansanloms/honkit-plugin-uml` is not loaded.

- Link to code example: https://github.com/ansanloms/honkit-test

## Expected results

`@ansanloms/honkit-plugin-uml` is load as honkit plugin

## Actual results

`@ansanloms/honkit-plugin-uml` is just ignored.

### PR DESCRIPTION
**Pull request by azu**
Fix to detect logic about scoped module.
Previously, @scope/honkit-plugin-name is just ignored

This commit fix to load scoped module like `@ansanloms/uml`

- https://github.com/ansanloms/honkit-test

fix #68

### CODE REVIEW

File: packages/honkit/src/models/pluginDependency.js [hunk 1]
```diff
@@ -89,25 +89,39 @@ PluginDependency.create = function (name, version, enabled) {
...
+            enabled: enabled,
+        });
     }
-
-    return new PluginDependency({
-        name: name,
-        version: version || DEFAULT_VERSION,
-        enabled: enabled,
-    });
+    throw new Error(`Can not parse this plugin syntax: ${s}`);
```
Comment (azu) [inline packages/honkit/src/models/pluginDependency.js:124]: Unexpected plugins throw an Error.

**Comment by azu** [comment]
Note: original GitBook does not support scoped module
So, similar issue smay exists in HonKit yet...
