### PR TITLE
fix!(asciidoc): correct include::./relative/path/from/content

### LINKED ISSUE #356: Error occured of "include file not found" by using asciidoc include directive.
## Summary

When using the include directive in an AsciiDoc file, an "include file not found" error occurs.

asciidoctor: ERROR: <stdin>: line 3: include file not found: D:/Document/share/TechnicalSiteGenerator/HonKit/resources/included1.txt
asciidoctor: ERROR: <stdin>: line 8: include file not found: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included2.txt
asciidoctor: ERROR: <stdin>: line 13: include file not found: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included3.txt

- HonKit version: 4.0.8

## Step to reproduce

1. make content1.adoc file like bellow.
```
----
include:: ./resources/included1.txt[]
----
```
2. build 
npx honkit build

- Link to code example:
[sample.zip](https://github.com/honkit/honkit/files/12062830/sample.zip)

## Expected results
This is the included text1 !

## Actual results
Unresolved directive in <stdin> - include::./resources/included1.txt[]

$ npx honkit build --log=debug
debug: readme found at README.adoc
debug: summary file found at SUMMARY.adoc
debug: cleanup folder "Q:\Document\share\TechnicalSiteGenerator\HonKit\_book"
info: 4 plugins are installed
info: 4 explicitly listed
info: plugin "search-pro-fixed" is loaded
info: plugin "highlight" is loaded
info: plugin "fontsettings" is loaded
info: plugin "theme-default" is loaded
info: found 3 pages
info: found 3 asset files
debug: calling hook "config"
debug: calling hook "init"
debug: copy assets from theme Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\@honkit\honkit-plugin-theme-default\_assets\website
debug: copy resources from plugin Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\gitbook-plugin-fontsettings\assets
debug: copy resources from plugin Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\@honkit\honkit-plugin-highlight\css
debug: copy resources from plugin Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\gitbook-plugin-search-pro-fixed\assets
debug: copy asset "chapter-1\resources\included1.txt"
debug: copy asset "chapter-1\resources\included2.txt"
debug: copy asset "chapter-1\resources\included3.txt"
debug: calling hook "page:before"
debug: calling hook "page:before"
debug: calling hook "page:before"
asciidoctor: ERROR: <stdin>: line 3: include file not found1: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included1.txt
asciidoctor: ERROR: <stdin>: line 8: include file not found1: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included2.txt
asciidoctor: ERROR: <stdin>: line 13: include file not found1: Q:/Doc
ument/share/TechnicalSiteGenerator/HonKit/resources/included3.txt
debug: calling hook "page"
debug: calling hook "page"
debug: calling hook "page"
debug: index page README.adoc
debug: index page chapter-1/README.adoc
debug: index page chapter-1/content1.adoc
debug: calling hook "finish:before"
debug: calling hook "finish"
debug: write search index
info: >> generation finished with success in 29.6s !

### PR DESCRIPTION
**Pull request by azu**
`project/src/main.adoc`:

```asciidoc
include::./dir/file.adoc[]
```

Previously, the `include::` path is relative path from working directory.
As a result, the `include::./dir/file.adoc` imported `project/dir/file.adoc`.

In this PR, the `include::` path is relative path from the content file path.
As a result, the `include::./dir/file.adoc` will import `project/src/dir/file.adoc`.

This is a bug fix, but the behaviour is changed and is therefore a BREAKING CHANGE.

- fix #356 
- fix https://github.com/GitbookIO/gitbook/pull/1733

### CODE REVIEW

File: packages/honkit/src/output/generatePage.ts [hunk 1]
```diff
@@ -56,25 +56,31 @@ function generatePage(output, page) {
...
                     })
 
-                    .then((output) => {
+                    .then(({ filePath, output }) => {
                         // console.log("page:render", Date.now() - start);
                         const content = output.getContent();
-
-                        return parser.parsePage(content).then((result) => {
+                        const baseDirectory = path.dirname(filePath);
+                        return parser.parsePage(content, { baseDirectory }).then((result) => {
```
Comment (azu) [inline packages/honkit/src/output/generatePage.ts:83]: This is main caller point

File: packages/@honkit/html/src/index.ts [hunk 2]
```diff
@@ -12,25 +12,77 @@ const htmlParser = {
...
 function compose(toHTML, fn) {
-    return function () {
-        const args = _.toArray(arguments);
-        args[0] = toHTML(args[0]);
-
-        return fn.apply(null, args);
+    return function (content: string, options: ToHTMLOptions) {
+        // e.g. convert asciidoc to html
+        const html = toHTML(content, options);
+        return fn.call(this, html);
```
Comment (azu) [inline packages/@honkit/html/src/index.ts:76]: add new option for `toHTML` function

File: packages/@honkit/html/src/index.ts [hunk 3]
```diff
@@ -12,25 +12,77 @@ const htmlParser = {
...
+    // it is custom page escaping function
+    prepare?: (content: string, options?: ToHTMLOptions) => string;
+};
+export type ParserInline = (
+    content: string,
+    options?: ToHTMLOptions
+) => {
+    content: string;
+};
+export type Parsers = {
```
Comment (azu) [inline packages/@honkit/html/src/index.ts:62]: Definf parser types

File: packages/@honkit/asciidoc/src/toHTML.ts [hunk 4]
```diff
@@ -1,18 +1,23 @@
...
+    }) as string;
+};
 
 // Render Asciidoc to HTML (inline)
-function asciidocToHTMLInline(content: string) {
-    return asciidoctor.convert(content, { doctype: "inline" });
-}
+const asciidocToHTMLInline: ToHTMLFunction = (content: string, options) => {
+    return asciidoctor.convert(content, { doctype: "inline", base_dir: options?.baseDirectory }) as string;
+};
```
Comment (azu) [inline packages/@honkit/asciidoc/src/toHTML.ts:18]: main fixes point.

Add `base_dir` option for convert asciidoc.

File: packages/honkit/src/__tests__/__snapshots__/snapshot-asciidoc.ts.snap [hunk 5]
```diff
@@ -179,7 +179,7 @@ exports[`asciidoc snapshot: chapter-1/content1.html 1`] = `
 <div class="sectionbody">
 <div class="listingblock">
 <div class="content">
-<pre>Unresolved directive in &lt;stdin&gt; - include::./resources/included1.txt[]</pre>
+<pre>This is the included text1 !</pre>
```
Comment (azu) [inline packages/honkit/src/__tests__/__snapshots__/snapshot-asciidoc.ts.snap]: Fix #356
